import { describe, expect, it, vi } from "vitest";
import { configView } from "@/lib/config-view";
import * as coreModule from "@curvebook/core";

describe("configView", () => {
  it("decodes valid base64 pool config and returns ConfigView with decoded info", () => {
    const address = "2bFH5q216w51UopEZP359NGGSUUeCwmycoBzP8Jc83at";
    const validB64 =
      "GmwOe3TmgSsGm4hX/quBhPtof2NGGMA12sQ53BrrO1WYoPAAAAAAAZIj0YdTDEhe4XiMlBfZVOxtQGbU7eMs4AyMrctJDuVqkiPRh1MMSF7heIyUF9lU7G1AZtTt4yzgDIyty0kO5WqgJSYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCwAAECcBAAEAAACAUQEAAAAAAAAAAAAAAAAAAAAAAAEBAAYAAQAAAABZBgEAAQAAAAAAAAAAAEE4wVzHQAAAgKkMrgIAAAAKYqyzKxoAALgehetRuB4FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgMakfo0DAACAxqR+jQMAAQAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABNe+brYIgRAgAAAAAAAAAAuB6F61G4HgUAAAAAAAAAAJHq16FPP2t4IQmf0uAAAACbV2lOqRpchLHE/v8AAAAAgMCvTkEqXA/BQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";
    const storedLines = ["Line 1", "Line 2"];

    const result = configView(address, validB64, storedLines);

    expect(result.info).not.toBeNull();
    expect(result.lines.length).toBeGreaterThan(0); // describeConfig returns lines
    expect(result.lines[0]).toContain("Flat");
    expect(result.toll).not.toBeNull();
    expect(result.toll).toHaveLength(10); // WINDOW_SLOTS = 10
    expect(result.toll![0]).toBe(25); // feeBps of the cliff fee (0.25%)
    expect(result.unit).toBe("slot"); // activationType === 0
    expect(result.json).not.toBeNull();
  });

  it("returns null info and storedLines when base64 decoding fails", () => {
    const address = "InvalidAddress";
    const invalidB64 = "!!!invalid base64!!!";
    const storedLines = ["Fallback line 1", "Fallback line 2"];

    const result = configView(address, invalidB64, storedLines);

    expect(result.info).toBeNull();
    expect(result.lines).toEqual(storedLines);
    expect(result.toll).toBeNull();
    expect(result.unit).toBe("slot");
    expect(result.json).toBeNull();
  });

  it("sets unit to 'second' when activationType is non-zero", () => {
    const address = "test-address";
    const validB64 = "dGVzdA=="; // doesn't matter, will be mocked

    // Mock decodePoolConfig to return a config with activationType === 1
    const mockDecodePoolConfig = vi.spyOn(coreModule, "decodePoolConfig").mockReturnValue({
      address,
      quoteMint: "So11111111111111111111111111111111111111112", // WSOL_MINT
      feeClaimer: "11111111111111111111111111111111",
      collectFeeMode: 0,
      activationType: 1, // non-zero activationType (timestamp-based instead of slot-based)
      tokenType: 0,
      tokenDecimal: 6,
      swapBaseAmount: 1000n,
      migrationQuoteThreshold: 0n,
      poolCreationFee: 0n,
      creatorTradingFeePct: 0,
      enableFirstSwapWithMinFee: false,
      migrationOption: 0,
      baseFee: {
        mode: 0,
        cliffFeeNumerator: 50_000_000n, // 50 bps
        firstFactor: 10,
        secondFactor: 1n,
        thirdFactor: 0n,
      },
      dynamicFee: false,
      curvePoints: 0,
    } as never);

    try {
      const result = configView(address, validB64, []);
      expect(result.unit).toBe("second"); // activationType !== 0, so should be "second"
      expect(result.info).not.toBeNull();
      expect(result.info?.activationType).toBe(1);
      expect(result.toll).not.toBeNull();
      expect(result.toll!.length).toBe(10);
    } finally {
      mockDecodePoolConfig.mockRestore();
    }
  });

  it("computes toll array with 10 fee values from baseFeeNumeratorAt", () => {
    const address = "2bFH5q216w51UopEZP359NGGSUUeCwmycoBzP8Jc83at";
    const validB64 =
      "GmwOe3TmgSsGm4hX/quBhPtof2NGGMA12sQ53BrrO1WYoPAAAAAAAZIj0YdTDEhe4XiMlBfZVOxtQGbU7eMs4AyMrctJDuVqkiPRh1MMSF7heIyUF9lU7G1AZtTt4yzgDIyty0kO5WqgJSYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCwAAECcBAAEAAACAUQEAAAAAAAAAAAAAAAAAAAAAAAEBAAYAAQAAAABZBgEAAQAAAAAAAAAAAEE4wVzHQAAAgKkMrgIAAAAKYqyzKxoAALgehetRuB4FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgMakfo0DAACAxqR+jQMAAQAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABNe+brYIgRAgAAAAAAAAAAuB6F61G4HgUAAAAAAAAAAJHq16FPP2t4IQmf0uAAAACbV2lOqRpchLHE/v8AAAAAgMCvTkEqXA/BQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";
    const storedLines: string[] = [];

    const result = configView(address, validB64, storedLines);

    expect(result.toll).not.toBeNull();
    expect(result.toll!.length).toBe(10);
    // For flat fee config, all slots should have the same fee (25 bps = 0.25%)
    for (let i = 0; i < 10; i++) {
      expect(result.toll![i]).toBe(25);
    }
  });

  it("correctly serializes ConfigInfo to JSON string with bigint support", () => {
    const address = "2bFH5q216w51UopEZP359NGGSUUeCwmycoBzP8Jc83at";
    const validB64 =
      "GmwOe3TmgSsGm4hX/quBhPtof2NGGMA12sQ53BrrO1WYoPAAAAAAAZIj0YdTDEhe4XiMlBfZVOxtQGbU7eMs4AyMrctJDuVqkiPRh1MMSF7heIyUF9lU7G1AZtTt4yzgDIyty0kO5WqgJSYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCwAAECcBAAEAAACAUQEAAAAAAAAAAAAAAAAAAAAAAAEBAAYAAQAAAABZBgEAAQAAAAAAAAAAAEE4wVzHQAAAgKkMrgIAAAAKYqyzKxoAALgehetRuB4FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgMakfo0DAACAxqR+jQMAAQAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABNe+brYIgRAgAAAAAAAAAAuB6F61G4HgUAAAAAAAAAAJHq16FPP2t4IQmf0uAAAACbV2lOqRpchLHE/v8AAAAAgMCvTkEqXA/BQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";
    const storedLines: string[] = [];

    const result = configView(address, validB64, storedLines);

    expect(result.json).not.toBeNull();
    expect(typeof result.json).toBe("string");
    // Verify it's valid JSON and doesn't contain "BigInt" strings
    const parsed = JSON.parse(result.json!);
    expect(parsed).toBeDefined();
    expect(result.json).not.toContain("[BigInt");
  });

  it("handles empty storedLines array and returns decoded config lines", () => {
    const address = "2bFH5q216w51UopEZP359NGGSUUeCwmycoBzP8Jc83at";
    const validB64 =
      "GmwOe3TmgSsGm4hX/quBhPtof2NGGMA12sQ53BrrO1WYoPAAAAAAAZIj0YdTDEhe4XiMlBfZVOxtQGbU7eMs4AyMrctJDuVqkiPRh1MMSF7heIyUF9lU7G1AZtTt4yzgDIyty0kO5WqgJSYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCwAAECcBAAEAAACAUQEAAAAAAAAAAAAAAAAAAAAAAAEBAAYAAQAAAABZBgEAAQAAAAAAAAAAAEE4wVzHQAAAgKkMrgIAAAAKYqyzKxoAALgehetRuB4FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgMakfo0DAACAxqR+jQMAAQAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABNe+brYIgRAgAAAAAAAAAAuB6F61G4HgUAAAAAAAAAAJHq16FPP2t4IQmf0uAAAACbV2lOqRpchLHE/v8AAAAAgMCvTkEqXA/BQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";

    const result = configView(address, validB64, []);

    // When decoding succeeds, storedLines are ignored and describeConfig is used
    expect(result.lines.length).toBeGreaterThan(0);
    expect(result.info).not.toBeNull();
  });

  it("returns storedLines as fallback when decoding fails with empty address", () => {
    const invalidB64 = "aGVsbG8gd29ybGQ="; // valid base64 but not a valid config
    const storedLines = ["Fallback 1", "Fallback 2", "Fallback 3"];

    const result = configView("", invalidB64, storedLines);

    // Even with valid base64, if decoding fails, we return storedLines
    expect(result.lines).toEqual(storedLines);
    expect(result.info).toBeNull();
  });
});
